In [3]:
import numpy as np

In [2]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.empty((3,3))

array([[8.45596650e-307, 1.33511969e-306, 8.06612616e-308],
       [4.45048724e-308, 1.11261570e-306, 3.22641142e-307],
       [3.11515773e-307, 1.60219035e-306, 1.02360527e-306]])

In [5]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.rand(6,6)

array([[0.52462783, 0.03623314, 0.06957776, 0.59810919, 0.90347141,
        0.46718891],
       [0.60084249, 0.11981614, 0.7627247 , 0.83250004, 0.52425679,
        0.75358914],
       [0.15824666, 0.35470803, 0.66413696, 0.6457335 , 0.69602617,
        0.87124306],
       [0.9238932 , 0.443626  , 0.1034986 , 0.74747754, 0.22756123,
        0.76675108],
       [0.89130893, 0.37926676, 0.59448679, 0.23075537, 0.04339153,
        0.22901606],
       [0.93354274, 0.43042068, 0.44978176, 0.64777377, 0.05702905,
        0.34832612]])

In [9]:
x = [1,2,3,4]

In [10]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [11]:
np.power(x,3)

array([ 1,  8, 27, 64], dtype=int32)

In [12]:
y = [-1,0,1,5]

In [13]:
np.maximum(x,y)

array([1, 2, 3, 5])

In [16]:
a = np.array([0,1,2500,2200])

In [17]:
np.where(a<=0,"NOT OK","OK")

array(['NOT OK', 'OK', 'OK', 'OK'], dtype='<U6')

In [18]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
np.sin(90*np.pi/180)                   # *np.pi/180 for evaluating values in degrees

1.0

In [40]:
b = np.arange(100,0,-2).reshape(2,5,5)       # 2*5*5 = 50 which is the number of elements in b

In [41]:
b

array([[[100,  98,  96,  94,  92],
        [ 90,  88,  86,  84,  82],
        [ 80,  78,  76,  74,  72],
        [ 70,  68,  66,  64,  62],
        [ 60,  58,  56,  54,  52]],

       [[ 50,  48,  46,  44,  42],
        [ 40,  38,  36,  34,  32],
        [ 30,  28,  26,  24,  22],
        [ 20,  18,  16,  14,  12],
        [ 10,   8,   6,   4,   2]]])

In [36]:
a = np.array([1,2,3,4,5])
b = np.array([10,11,12,13,14])
np.add(a,b)

array([11, 13, 15, 17, 19])

In [20]:
np.random.default_rng(1)    # create instance of default random number generator
b= rg.random((2,3))
b

array([[0.89471586, 0.42271691, 0.58950206],
       [0.02449068, 0.67345989, 0.91908862]])

In [22]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [23]:
a.sum()

15

In [24]:
a.max()

5

In [25]:
a.min()

1

In [27]:
a.cumsum()                   #cumulative sum along each row

array([ 1,  3,  6, 10, 15], dtype=int32)

In [28]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [37]:
a = np.floor(10*rg.random((3,4)))
a

array([[8., 8., 6., 2.],
       [7., 2., 8., 0.],
       [8., 1., 3., 3.]])

In [38]:
a.reshape((6,2))            # returns modified form of array

array([[8., 8.],
       [6., 2.],
       [7., 2.],
       [8., 0.],
       [8., 1.],
       [3., 3.]])

In [39]:
a.ravel()        # returns the array, flattened

array([8., 8., 6., 2., 7., 2., 8., 0., 8., 1., 3., 3.])

In [40]:
a.T                   #returns trasnspose

array([[8., 7., 8.],
       [8., 2., 1.],
       [6., 8., 3.],
       [2., 0., 3.]])

In [42]:
a.resize((2,6))            # modifies the array itself

In [43]:
a

array([[8., 8., 6., 2., 7., 2.],
       [8., 0., 8., 1., 3., 3.]])

In [46]:
a.reshape((3,-1))

array([[8., 8., 6., 2.],
       [7., 2., 8., 0.],
       [8., 1., 3., 3.]])

In [51]:
a = np.floor(10*rg.random((2,2)))
a

array([[6., 5.],
       [0., 4.]])

In [54]:
b = np.floor(10*rg.random((2,2)))
b

array([[4., 2.],
       [8., 1.]])

In [55]:
np.vstack((a,b))

array([[6., 5.],
       [0., 4.],
       [4., 2.],
       [8., 1.]])

In [56]:
np.hstack((a,b))

array([[6., 5., 4., 2.],
       [0., 4., 8., 1.]])

In [57]:
a

array([[6., 5.],
       [0., 4.]])

In [58]:
b

array([[4., 2.],
       [8., 1.]])

In [60]:
np.vstack((a,b))

array([[6., 5.],
       [0., 4.],
       [4., 2.],
       [8., 1.]])

In [61]:
np.hstack((a,b))

array([[6., 5., 4., 2.],
       [0., 4., 8., 1.]])

In [64]:
np.column_stack((a,b))

array([[6., 5., 4., 2.],
       [0., 4., 8., 1.]])

In [65]:
np.row_stack((a,b))

array([[6., 5.],
       [0., 4.],
       [4., 2.],
       [8., 1.]])

In [67]:
np.hsplit(a,2)  #splits the selected array into smaller arrays

[array([[6.],
        [0.]]),
 array([[5.],
        [4.]])]

In [68]:
a

array([[6., 5.],
       [0., 4.]])

In [71]:
c = a.view()             # c is a view of the data owned by a

In [70]:
c

array([[6., 5.],
       [0., 4.]])

In [73]:
d = a.copy()     # a new array object with new data is created
d                # d doesn't share anything with a

array([[6., 5.],
       [0., 4.]])

In [76]:
numbers = np.array([-4,5.5,0,23,-27.7])

In [77]:
np.absolute(numbers)

array([ 4. ,  5.5,  0. , 23. , 27.7])

In [78]:
np.ceil(numbers)

array([ -4.,   6.,   0.,  23., -27.])

In [79]:
np.floor(numbers)

array([ -4.,   5.,   0.,  23., -28.])

In [81]:
np.round(numbers)

array([ -4.,   6.,   0.,  23., -28.])

In [82]:
np.divide(numbers,5)

array([-0.8 ,  1.1 ,  0.  ,  4.6 , -5.54])

In [83]:
np.multiply(numbers,5)

array([ -20. ,   27.5,    0. ,  115. , -138.5])

In [84]:
np.add(numbers,5)

array([  1. ,  10.5,   5. ,  28. , -22.7])

In [85]:
np.subtract(numbers,5)

array([ -9. ,   0.5,  -5. ,  18. , -32.7])

In [89]:
np.append(numbers,100)

array([ -4. ,   5.5,   0. ,  23. , -27.7, 100. ])

In [91]:
np.delete(numbers,0)

array([  5.5,   0. ,  23. , -27.7])

In [100]:
np.insert(numbers,5,100)

array([ -4. ,   5.5,   0. ,  23. , -27.7, 100. ])

In [103]:
numbers.tolist()

[-4.0, 5.5, 0.0, 23.0, -27.7]